version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  bot-api:
    build: https://github.com/bloxlink/bot-api.git
    depends_on:
      - redis
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=${REDIS_HOST-redis}
      - AUTH=${BOT_API_AUTH-''}
      - MONGO_URL=${MONGO_URL:?err}

  bloxlink-http:
    build: .
    depends_on:
      - redis
      - bot-api
    environment:
      - BOT_API=bot-api
      - BOT_API_AUTH=${BOT_API_AUTH-''}
      - REDIS_HOST=${REDIS_HOST-redis}
      - MONGO_URL=${MONGO_URL:?err}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID:?err}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY:?err}
      - DISCORD_TOKEN=${DISCORD_TOKEN:?err}
    ports: 
      - "8010:8010"
  