[tool.poetry]
name = "bloxlink-http"
version = "0.1.0"
description = "An http interactions worker for bloxlink"
authors = ["kaj <40004347+KAJdev@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
motor = "^3.0.0"
hiredis = "^2.0.0"
redis = "^4.3.3"
dnspython = "^2.2.1"
psutil = "^5.9.1"
snowfin = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
